### ISSUE TITLE
Create and Store Questions in Question Bank

### ISSUE THREAD

**Issue by DeLucaJ** [CSC307Fall2019/Group-5#16]
As a TEACHER, I want to be able to create and store questions in a question bank

### Tasks
- [x] Bank Table
- [x] Creating Topics
- [x] Creating Subtopics
- [x] Creating Questions
- [x] Deleting Questions from Bank

**Comment by jon77p** [comment]
For tracking, the following PRs applied to this Sprint:
#37 
#38
